[build]
  base = "/"
  publish = "static_site"
  command = "pip install -r requirements.txt && python app.py init_db"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin/prazos"
  to = "/admin_prazos.html"
  status = 200
